### ISSUE TITLE
Link to individual Guide articles?

### ISSUE THREAD

**Issue by lorensr** [meteor/docs#1]
In addition to the general link already in the intro.

For instance from somewhere in here:

![image](https://cloud.githubusercontent.com/assets/251288/15133896/42813a4c-1635-11e6-8ca5-8a02bc70c338.png)

to here:

http://guide.meteor.com/blaze.html

**Comment by lorensr** [comment]
Oh. meteor.com/blaze now redirects to the Guide. Perhaps applicable to other sections

**Comment by tmeasday** [comment]
Yeah we should definitely do this

**Comment by ttbohemian** [comment]
Is still needed help for this issue? :)

**Comment by lorensr** [comment]
Blaze has it's own docs & guide now, which are linked. Looks like the major topics like Collections, Methods, etc have links to the Guide. @ttbohemian if you find any specific places you think links to Guide articles would be helpful, please submit at PR! 😊
