### ISSUE TITLE
Improve DDPRateLimiter docs and add extra examples

### ISSUE THREAD

**Issue by abernix** [meteor/docs#103]
@avalanche1 commented on [Tue Jan 26 2016](https://github.com/meteor/meteor/issues/6087)

Specifying a rule for each and every method and subscription is not exactly friendly.
If a rule is specified, it should override global rule.

---

@stubailo commented on [Thu Jan 28 2016](https://github.com/meteor/meteor/issues/6087#issuecomment-175922052)

The rule adding mechanism is quite flexible - are you interested in:

1. Adding a global rate limit that uses one counter for all methods and subscriptions
2. Adding a rate limit that counts calls _per_ method or subscription
3. A rate limit per method or subscription, per user or per IP?

Basically, there isn't a simple default because different applications will want different options from the above. All of them are possible with the current DDPRateLimiter API, which is a bit poorly documented in retrospect but can do a lot of stuff. I can show you how to do what you're asking for.

---

@avalanche1 commented on [Fri Jan 29 2016](https://github.com/meteor/meteor/issues/6087#issuecomment-176572604)

Thanks!
1st off I'd like to know how to set a global limit that applies same rule to every method and sub, using different counter for each.
2ndly it'd be nice to learn how to do the same but with a compound counted (point 1 in ur list). 
A rate limit per user or per IP (using matcher field) is rather obvious from the docs, I guess.

---

@zeari commented on [Sat Oct 22 2016](https://github.com/meteor/meteor/issues/6087#issuecomment-255517123)

hi, anything going on with this? The basic login example doesnt really cut it when you want to limit guest users or limit subscriptions.

---

@abernix commented on [Tue Nov 08 2016](https://github.com/meteor/meteor/issues/6087#issuecomment-259182640)

@zeari Unfortunately, this is a docs issue that hasn't been resolved yet.  Please try asking for help with your specific problem on the [Meteor forums](http://forums.meteor.com/) under `help`.  Someone will likely be able to advise there.

---

@stubailo commented on [Tue Nov 08 2016](https://github.com/meteor/meteor/issues/6087#issuecomment-259237306)

If you get a good answer please help with a PR!

By the way, should we move this issue to https://github.com/meteor/docs?

**Comment by stubailo** [comment]
@abernix do you have some sort of tool to move issues?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
