### ISSUE TITLE
[wip] Docs Not Generating for 1.4.2.1

### ISSUE THREAD

**Issue by abernix** [meteor/docs#105]
When I bumped the code version for the 1.4.2.1 release [per this commit](https://github.com/meteor/docs/commit/abd25d1fe46bdb73069ccfdc0148db4730c34843), I soon found that updated docs weren't posted after deployment.  Upon inspection, the deploy looked like it worked, but didn't fail properly because [this was still necessary](https://github.com/meteor/hexo-s3-deploy/commit/278a408c38997b08679779baec805c44a99a78ed).

That led to finding that the `Assets.getText` was missing for some reason, but upon inspection of the failing file, I found that the trailing function comma added in [here in 1.4.2.1](https://github.com/meteor/meteor/commit/940cc4f4d63524bda6d591e2ec76f5d9cfbe4839#diff-0f00f30d4b45f5a773d05a409badc311R572) was causing JSdoc to fail.  Ultimately, I think the trailing function comma is ES8 which wouldn't be supported by the JSDoc that we're using for Docs.

So, for similar reasons that [this commit was necessary](https://github.com/meteor/jsdoc/commit/c564f2803f76ab12e84f290d6d5dd12a008a45c4) (which is no longer necessary, as JSDoc is now fully compliant with ES7), I've created this branch: https://github.com/abernix/jsdoc/tree/espree-3.3

I could use my `abernix` repo on this project, but probably more ideally (to keep this in `meteor/jsdocs`), if someone with permission to meteor/jsdocs can (essentially):

```sh 
cd meteor/jsdoc # or clone or whatever
git checkout -b espree-3.3
git pull https://github.com/abernix/jsdoc.git espree-3.3
git push # ... 
```

Then we can update [this line](https://github.com/meteor/docs/blob/657860d841ead74655680530b3f010b47675a7a6/package.json#L21).

(I would have done a pull request on `espree-3.1`, but it would have been a merge conflict and probably more difficult)

/cc @tmeasday

**Comment by tmeasday** [comment]
@abernix : done - https://github.com/meteor/jsdoc/tree/espree-3.3

**Comment by tmeasday** [comment]
Fixed, thanks very much @abernix !
