### ISSUE TITLE
Emails are not published to clients

### ISSUE THREAD

**Issue by hwillson** [meteor/docs#114]
Moving this over from meteor/meteor#4685. Comment https://github.com/meteor/meteor/issues/4685#issuecomment-119331937 gives a breakdown of the issues and what needs to be fixed.

----

(originally reported by @Zane-XY)

From the documentation http://docs.meteor.com/#/full/meteor_users

> By default, the current user's username, emails and profile are published to the client.

but when I run `Meteor.user()` in the client console, I didn't get the emails field:

```
Meteor.user()
Object { _id: "vK5ddWtypCewCwbSL", profile: Object }
```

I am using account-google, with autopublish removed.

**Comment by lorensr** [comment]
`emails` field should be published:

https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L715-L719

And `accounts-google` only removes the email field for other users:

https://github.com/meteor/meteor/blob/devel/packages/accounts-google/google.js#L37

Looking at Sashko's comment:
- 1: do accounts-* use `emails`? if not, can note that in the docs.
- 2: example user doc doesn't have `services.password`
- 3: #121

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
