### ISSUE TITLE
Layout problems with docs of older versions

### ISSUE THREAD

**Issue by klaussner** [meteor/docs#116]
Since the last update, all older versions of the docs, for example http://docs.meteor.com/v1.4.1/, have some layout problems. :upside_down_face: 

![meteor-docs](https://cloud.githubusercontent.com/assets/1312807/22588432/13bdc1ee-ea06-11e6-8999-88d82055d680.png)

**Comment by lorensr** [comment]
same problem with older versions of the guide:

https://guide.meteor.com/v1.3/

cc @abernix

**Comment by klaussner** [comment]
I think this is fixed. All versions of the Docs and the Guide are looking good. 👍

**Comment by abernix** [comment]
Ah, yes.  I fixed this thanks to your report actually, @klaussner.  Thank you! :)  (And thanks for the follow-up check)
