### ISSUE TITLE
Hard to discover that collection observes run synchronously, but Tracker autoruns are asynchronous

### ISSUE THREAD

**Issue by hwillson** [meteor/docs#117]
Migrating this issue over from meteor/meteor#4339. Doc changes are recommended to address this issue - see https://github.com/meteor/meteor/issues/4339#issuecomment-101413560:

> However, we don't do a great job of documenting that observe callbacks run synchronously, so that could be a good place to start.

----

(originally reported by @mitar)

If I use on the client autorun to observe a reactive variable and observe a collection and I modify variable and after it a collection, collection change through observe is propagated first. This surprises quite a bit. It is in some way clear because observes are run synchronously, while reactivity happens on flushes, but it is hard to reason about this and discover it in a larger application where you mix both reactive variables and local collections as another more complex reactive source.

Reproduction: https://github.com/mitar/meteor-issue4339

When run, the output in the web console is:

```
variable value null
collection value undefined
collection observe value Object {value: true, _id: "hXrmCZfbaFzSGCAoZ"}
variable value true
collection value Object {value: true, _id: "hXrmCZfbaFzSGCAoZ"}
```

I would expect that it would be:

```
variable value null
collection value undefined
variable value true
collection value Object {value: true, _id: "hXrmCZfbaFzSGCAoZ"}
collection observe value Object {value: true, _id: "hXrmCZfbaFzSGCAoZ"}
```

In the order autoruns and observes were defined.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
