### ISSUE TITLE
Briefly explain or link to Fibers in docs

### ISSUE THREAD

**Issue by hwillson** [meteor/docs#119]
Migrating over from meteor/meteor#3982. This issue was created before the Guide came to life, and some sections of the Guide help with this (e.g. [Asyncronous Callbacks](https://guide.meteor.com/using-npm-packages.html#async-callbacks)), but it might be a good idea to expand on Fiber use in the docs a (or Guide) bit further. I'll open it here for now anyways - please close / migrate as you see fit!

----

(originally reported by @dandv)

http://docs.meteor.com/#/full/ mentions "fiber" four times, but the concept isn't explain. Since Fibers are the mechanism behind an important design decision and a differentiator for Meteor vs. Node-based stacks, it would be helpful to explain the concept.

> In Meteor, your server code runs in a single thread per request, not in the asynchronous callback style typical of Node. We find the linear execution model a better fit for the typical server code in a Meteor application.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
