### ISSUE TITLE
Document create --full and --bare

### ISSUE THREAD

**Issue by merlinpatt** [meteor/docs#122]
This PR introduced `--full` and `--bare` to the `create` command https://github.com/meteor/meteor/pull/7807

But the docs still only list `create` with only the `--package` option
http://docs.meteor.com/commandline.html

**Comment by aliogaili** [comment]
I think the Meteor Guide need to be updated to include the new flags since it create the guide recommended structure.

**Comment by brooksbecton** [comment]
Looks like this is already done

f8509126e870f2155e736b17dcc94e86e129a739

**Comment by merlinpatt** [comment]
I think that documentation could be expanded. It's not very clear what an empty or full project would entail or why you would choose those.

**Comment by brooksbecton** [comment]
*It looks like the packages are the same for `--full` and `--bare` so I would believe the only difference is the file structure. `--bare` provides files absolutely necessary for meteor while `--full` follows a structure similar to the [Meteor Guide](https://guide.meteor.com/), but more specifically [The Application Structure](https://guide.meteor.com/structure.html#javascript-structure) section.

I would definitely note in the docs that both the flagged options assume the view will use blade.For example, I use React so I wouldn't be using the blaze layout or router and I may be more prone to use Jest for testing instead of mocha. 

Here are the outputs of `meteor list` on the boilerplates created (_with packages that were found in all three removed_). 

```
FULL
blaze-html-templates              1.1.2  Compile HTML templates into reactive UI with Meteor Blaze
johanbrook:publication-collector  1.0.10  Test a Meteor publication by collecting its output.
kadira:blaze-layout               2.3.0  Layout Manager for Blaze (works well with FlowRouter)
kadira:flow-router                2.12.1  Carefully Designed Client Side Router for Meteor
less                              2.7.9  Leaner CSS language
practicalmeteor:mocha             2.4.5_6  Write package tests with mocha and run them in the browser or from the command line with spacejam.

BARE
blaze-html-templates              1.1.2  Compile HTML templates into reactive UI with Meteor Blaze
johanbrook:publication-collector  1.0.10  Test a Meteor publication by collecting its output.
kadira:blaze-layout               2.3.0  Layout Manager for Blaze (works well with FlowRouter)
kadira:flow-router                2.12.1  Carefully Designed Client Side Router for Meteor
less                              2.7.9  Leaner CSS language
practicalmeteor:mocha             2.4.5_6  Write package tests with mocha and run them in the browser or from the command line with spacejam.

NORMAL 
autopublish            1.0.7  (For prototyping only) Publish the entire database to all clients
blaze-html-templates   1.1.2  Compile HTML templates into reactive UI with Meteor Blaze
insecure               1.0.7  (For prototyping only) Allow all database writes from the client
shell-server           0.2.4  Server-side component of the `meteor shell` command.
```

_*I'm still brand new to Meteor, so feel free to correct me here._

**Comment by klaussner** [comment]
@brooksbecton The `--bare` template doesn't use Blaze or third-party packages (like `kadira:flow-router`). This is the output I get from `meteor --list` for a project created with `meteor create --bare`:

```
ecmascript             0.8.2  Compiler plugin that supports ES2015+ in all .js files
es5-shim               4.6.15  Shims and polyfills to improve ECMAScript 5 support
meteor-base            1.1.0  Packages that every Meteor app needs
mobile-experience      1.0.4  Packages for a great mobile user experience
mongo                  1.2.0  Adaptor for using MongoDB and Minimongo over DDP
reactive-var           1.0.11  Reactive variable
shell-server           0.2.4  Server-side component of the `meteor shell` command.
standard-minifier-css  1.3.4  Standard css minifier used with Meteor apps by default.
standard-minifier-js   2.1.1  Standard javascript minifiers used with Meteor apps by default.
static-html            1.2.2  Define static page content in .html files
tracker                1.1.3  Dependency tracker to allow reactive callbacks
```

**Comment by abernix** [comment]
If there is a particular part of this which could be more clear, please consider making a pull request to the docs!

**Comment by merlinpatt** [comment]
I would like to see the differences documented similarly to the above. So listing the different packages you get, as well as the folder structure.

However, this would make `meteor create` section long, probably longer than other shell command sections. Would that be confusing or otherwise problematic?

If not, then I'd be happy to add them.

**Comment by brooksbecton** [comment]
Added a PR here: #161

**Comment by jankapunkt** [comment]
I found that although it has been implemented it is displayed in the browser like this:

|| Default | --bare | --full | --minimal | |——————–|——–|—|—| |autopublish| X | | | | |blaze-html-templates| X | |X | | |ecmascript|X|X|X|X| |es5-shim|X|X|X|X| |insecure|X||| | |johanbrook:publication-collector|||X| | |kadira:blaze-layout|||X| | |kadira:flow-router|||X| | |less|||X| | |meteor||||X| |meteor-base|X|X|X| | |mobile-experience|X|X|X| | |mongo|X|X|X| | |practicalmeteor:mocha|||X| | |reactive-var|X|X|X| | |server-render||||X| |shell-server|X|X||X| |standard-minifier-css|X|X|X|X| |standard-minifier-js|X|X|X|X| |static-html||X||X| |tracker |X|X|X| | |webapp | | | |X|

Source: https://docs.meteor.com/commandline.html#meteorcreate

Looks like a formatting issue.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
