### ISSUE TITLE
Demonstrate that `sort` can be a `Function`

### ISSUE THREAD

**Issue by abernix** [meteor/docs#123]
As implemented in https://github.com/meteor/meteor/pull/7164 and https://github.com/meteor/meteor/pull/6008, the documentation for [Sort Specifiers](https://docs.meteor.com/api/collections.html#sortspecifiers) should be updated with information on how this can be used.

Suggested by @mitar in https://github.com/meteor/meteor/issues/2730#issuecomment-278741467, :pray:

**Comment by mitar** [comment]
One [interesting example how one can misuse this](https://stackoverflow.com/questions/42071737/is-it-possible-to-sort-a-collection-only-once-and-then-keep-that-order-intact-de/42102177#42102177).

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
