### ISSUE TITLE
Document registerLoginHandler

### ISSUE THREAD

**Issue by hwillson** [meteor/docs#130]
Migrating this over from meteor/accounts#15. There isn't much detail there, but `Accounts.registerLoginHandler` does appear to be missing from the docs.

----

(originally reported by @llvasconcellos)

Why registerLoginHandler is not on any documentation?

**Comment by lodi-g** [comment]
+1

**Comment by harzkr** [comment]
+1

**Comment by Hobbit44** [comment]
+1

**Comment by asedsami** [comment]
+1

**Comment by pisti2010** [comment]
+1

**Comment by ibrahimhist** [comment]
+1

**Comment by steveAtInstant** [comment]
+1

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
