### ISSUE TITLE
Accounts docs don't mention import { Accounts } ...

### ISSUE THREAD

**Issue by hwillson** [meteor/docs#132]
Related issue: meteor/meteor#8559

Reading over the Accounts docs, it doesn't look like we ever mention that the default `Accounts` object can be accessed using `import { Accounts } from 'meteor/accounts-base';`. The `Accounts` object is discussed briefly via the [Accounts (multi-server)](http://docs.meteor.com/api/accounts-multi.html) intro text ...

> The accounts-base package exports two constructors, called AccountsClient and AccountsServer, which are used to create the Accounts object that is available on the client and the server, respectively.
>
> This predefined Accounts object (along with similar convenience methods of Meteor, such as Meteor.logout) is sufficient to implement most accounts-related logic in Meteor apps. Nevertheless, these two constructors can be instantiated more than once, to create multiple independent connections between different accounts servers and their clients, in more complicated authentication situations.

... but we're missing a concrete ES2015 example of how to reference the `Accounts` object. People are trying to access the `AccountsCommon` object directly using the first listed import statement of `import { AccountsCommon } from 'meteor/accounts-base'`, which can be a bit misleading.

**Comment by dr-dimitru** [comment]
It's [mentioned here](http://docs.meteor.com/api/accounts.html#Accounts-ui-config). I'm agree on moving this to the top of article

**Comment by hwillson** [comment]
Oh wow - that's definitely buried! Thanks @dr-dimitru!

**Comment by dr-dimitru** [comment]
@hwillson wow that was quick.

For me more confused was to understand the difference between `Accounts` and `AccountsCommon` and what there is no reason to use `AccountsCommon`, `AccountsServer` and `AccountsClient` directly (*unless you're writing a package or hack into internals*), and mostr of the time developers should use `Accounts`.

**Comment by abernix** [comment]
Perhaps it's just a matter of using the [`@augments` / `@extends` JSDoc syntax](http://usejsdoc.org/tags-augments.html)?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
