### ISSUE TITLE
Should Blaze links take you to corresponding page in Blaze Docs?

### ISSUE THREAD

**Issue by jkd65** [meteor/docs#134]
Should Blaze links take you to corresponding page in Blaze Docs instead of the Meteor/Blaze where users still have to search for what they are looking for?

**Comment by lorensr** [comment]
I think so, sounds useful! PR welcome

**Comment by jkd65** [comment]
Alright I will try and do this!

**Comment by jkd65** [comment]
I guess I was looking at the Guide, not the API. Will try and look through to see if it applies here.

**Comment by lorensr** [comment]
Links I could find in docs are good, thanks for the [Guide PR](https://github.com/meteor/guide/pull/629) 😊
