### ISSUE TITLE
I use the code on my site: https://cj.tn

### ISSUE THREAD

**Issue by i06** [meteor/docs#137]
Could I use the code to build my site( https:// cj.tn )?
I you refuse it, I will offline my site.

**Comment by abernix** [comment]
I assume you're talking about the theme.  I'm not sure what our license will be on this or where it came from (it's currently unlisted), but https://github.com/meteor/hexo-theme-meteor/ is the better place to ask.

**Comment by lorensr** [comment]
@i06 here's the existing issue: 

https://github.com/meteor/hexo-theme-meteor/issues/23
