### ISSUE TITLE
Meteor.bindEnvironment is not documented

### ISSUE THREAD

**Issue by mitar** [meteor/docs#139]
It is mentioned few times:
* https://docs.meteor.com/api/timers.html
* https://guide.meteor.com/using-npm-packages.html#bind-environment

But it is not documented anywhere in reference/API documentation.

cc @zimme

**Comment by archywilhes** [comment]
For example, I did `const updateUser = Meteor.bindEnvironment(Meteor.users.update)` hoping to use .update in a callback passed to another library's function but I got 

`Exception in callback of async function: TypeError: this._isRemoteCollection is not a function`

indicating that the binding is not properly done.

**Comment by archywilhes** [comment]
aw I see. you need to bind the actual callback. binding any function called in the callback won't do.

**Comment by maxfriedmann** [comment]
Now it is: https://guide.meteor.com/using-npm-packages.html#bind-environment

**Comment by lorensr** [comment]
Thanks Max!
