### ISSUE TITLE
Unclear semantics of stub execution

### ISSUE THREAD

**Issue by hwillson** [meteor/docs#153]
Migrated this from https://github.com/meteor/meteor/issues/4221. We might want to update the [Methods](https://docs.meteor.com/api/methods.html) docs to mention that stubs run synchronously before sending the RPC to the server. As alluded to in https://github.com/meteor/meteor/issues/4221#issuecomment-94944410, the Methods docs currently mention "If you do define a stub, when a client invokes a server method it will also run its stub in parallel.", which is a bit misleading.

----

(originally posted by @mitar)

From documentation it is unclear if stub execution on the client is assured to happen in a blocking way or not. So if I do:

```js
Meteor.call('foobar')
```

On the client, and `foobar` method has a stub. Can I expect that the stub will be always called before program flow gets after the `Meteor.call` call? Is this specified?

Alternatively, is there a difference on the client between:

```js
Meteor.call('foobar')
```

And:

```js
Meteor.defer(function () {
  Meteor.call('foobar')
});
```

Documentation just says that `Meteor.call` will always return `undefined` on the client.

(So I am talking out of the simulation context here.)

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
