### ISSUE TITLE
Document the fact that cursor.observe runs the initial added callbacks in the current computation, but not any subsequent callbacks

### ISSUE THREAD

**Issue by hwillson** [meteor/docs#156]
Migrated from https://github.com/meteor/meteor/issues/3137. I've verified this is still the case with Meteor 1.5.1.

----

(originally reported by @michaelstephendavies)

When calling `cursor.observe` inside a reactive computation, the initial synchronous `added` callbacks are run inside that computation, but any further async callbacks are not.

```js
var coll = new Mongo.Collection(null);
coll.insert({x: 3});
Tracker.autorun(function () {
  coll.find().observe({
    added: function (doc) {
      console.log(doc.x, Tracker.active);
    }
  });
}); // logs "3 true"
coll.insert({x: 4}); // logs "4 false"
```

I find this quite surprising. In retrospect, it sort of makes sense - although personally, I expected neither of them to run in computations. Any way, I think it's non-obvious enough to justify being documented in http://docs.meteor.com/#/full/observe_changes, recommending wrapping the callback in `Tracker.nonreactive` if you want consistency.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
