### ISSUE TITLE
Document that the loginExpirationInDays config needs to be run on both client and server

### ISSUE THREAD

**Issue by hwillson** [meteor/docs#158]
Migrating this over from https://github.com/meteor/meteor/issues/3656. Comment https://github.com/meteor/meteor/issues/3656#issuecomment-73805579 mentions that this should be better documented.

----

(originally reported by @mariorodriguespt)

I want to allow users to check "Remember me" at the login page. According to the [documentation](http://docs.meteor.com/#/full/accounts_config), I can run this code anywhere but I don't see this behaviour working in the browser.

Running on the client:

```
Accounts.config({
  loginExpirationInDays: null
});
```

When I check localStorage I get: Meteor.loginTokenExpires : Sat Feb 07 2015 06:34:22 GMT+0000 (WET)

It doesn't matter which number I set on the client, the server defines the expiration date. Bug in the docs?
When I don't set a configuration on the server, I get the message on the console: `Accounts.config was called on the client but not on the server; some configuration options may not take effect.`

When I try to set a new value for `loginExpirationInDays` I get the error: `Error: Can't set 'loginExpirationInDays' more than once`

I want to implement the "remember me" feature but It seems like Meteor doesn't provides it. 

If I was able to set the expiration date on the client or pass some flag to the login method, I could implement it. I also noticed that `services.resume.loginTokens` contains a creation date `when` but I don't see an expiration date. So, does a loginToken expires based on `when` + `loginExpirationInDays` date?

How can I safely implement the `Remember me` feature?
Am I missing something?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
