### ISSUE TITLE
BrowserPolicy

### ISSUE THREAD

**Issue by abernix** [meteor/docs#16]
Moved from meteor/meteor#6766:

The solution was that in order to use `BrowserPolicy` it must be included!  But from where!?

**From Here:**

```
import { BrowserPolicy } from 'meteor/browser-policy-common';
```

I guess this entire package needs to be documented?  There is some debate in #6766 about whether it should be from `browser-policy-common` or `browser-policy`, but either way, this needs to be documented and it's likely that it can be exported from both for reverse-compatibility.
##### Original Issue

I have installed the browser-policy package (`meteor add browser-policy`) and set up some rules:

```
BrowserPolicy.framing.disallow();
BrowserPolicy.content.disallowEval();
BrowserPolicy.content.disallowObject();
BrowserPolicy.content.disallowInlineScripts();
BrowserPolicy.content.disallowFont();
```

The Meteor Guide [recommends the Airbnb javascript style guide](http://guide.meteor.com/code-style.html#style-guide), which requires that `BrowserPolicy` be defined/imported before making the above declarations. Not being able to import the `BrowserPolicy` variable results in ESLint errors, which causes the test suite (`meteor npm run test`) to fail.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
