### ISSUE TITLE
Meteor.server is not documented and therefore doesn't appear in Meteor.d.ts

### ISSUE THREAD

**Issue by sdarnell** [meteor/docs#168]
The new [ddp-graceful-shutdown package](https://github.com/meteor/ddp-graceful-shutdown)  is documented that you have to pass Meteor.server when initialising it.  But this member isn't documented, and it is also not declared in Meteor.d.ts.

This means that the instructions for ddp-graceful-shutdown don't work for Typescript users.

The work-around is simply to use Meteor['server'] instead, but this is not ideal. It seems that it should be documented as some legitimate packages might need it. It was renamed from default_server about 4 years ago (as a DDP convenience).
https://github.com/meteor/meteor/blob/84ed04b8f3b99cf16b5540f2e0193d47e4f8ccf6/packages/ddp-server/server_convenience.js#L6

I notice that the accounts system (oauth_common.js, accounts_server.js), and ddp-heartbeat package also use it. 

Now, there's a possibility that it was never intended to be exposed. But if that's the case, at least the ddp-graceful-shutdown package shouldn't require it.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
