### ISSUE TITLE
Update Package Server API Docs

### ISSUE THREAD

**Issue by blongstreth** [meteor/docs#169]
I have been working with the Meteor Package Server API (via the [Stratosphere](https://github.com/sebakerckhof/stratosphere) project) and I have found a discrepancy between the API and the [docs](https://github.com/meteor/docs/blob/master/long-form/package-server-api.md).  Specifically, the object `Versions.source` in [package-server-api.md](https://github.com/meteor/docs/blob/master/long-form/package-server-api.md) doesn't have the `hash` field. It has the following "hash" related fields instead:
```
tarballHash: (String) SHA256 hash of the tarball
treeHash: (String) SHA256 hash of the contents of the tarball
```

My hope is that the API docs are just wrong and that there wasn't a database update.

There maybe more issues but this is the main one.  My hope is that the API documentation can stay up-to-date and mostly static because I am trying to support a private Meteor package server which supports caching meteor-bootstrap installers and packages.  Basically, I have to provide similar functionality as [Artifactory](https://www.jfrog.com/artifactory/) which allows for complete build isolation from the internet in the event Meteor package server goes away or is down.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
