### ISSUE TITLE
Document Mongo.setConnectionOptions limitations

### ISSUE THREAD

**Issue by hwillson** [meteor/docs#173]
Reference: https://github.com/meteor/meteor/issues/7455

Instead of addressing this in code, we'll document this limitation, as well as the suggested workaround.

**Comment by hwillson** [comment]
And we should probably also add `Mongo.setConnectionOptions` to the API docs ... 😳

**Comment by ephemer** [comment]
Is this official API still? Will need this as of next week. Thanks!

**Comment by SkariDamm** [comment]
Any progress on this? Tagging @filipenevola since I'm unsure if @hwillson is still an active contributor.
