### ISSUE TITLE
Clarify that Meteor.methods generate the same _id on the client and server

### ISSUE THREAD

**Issue by abernix** [meteor/docs#19]
Moved from meteor/meteor#4780

I couldn't find this anywhere in the docs, so I think it's still undocumented.  Please close if you know of its whereabouts.

**Sashko** commented on [Tue Jul 21 2015](https://github.com/meteor/meteor/issues/4780)

Except for this trello card: https://trello.com/c/moiiS2rP/57-pattern-for-creating-multiple-database-records-from-a-method

---

**Justin** commented on [Tue Jul 21 2015](https://github.com/meteor/meteor/issues/4780#issuecomment-123137709)

Indeed, https://github.com/meteor/meteor/blob/devel/packages/ddp/DDP.md says that it is deliberately undocumented 'pending stabilization'.  Perhaps we can now consider it stable and document it!

---

**Sashko** commented on [Tue Jul 21 2015](https://github.com/meteor/meteor/issues/4780#issuecomment-123211881)

Yep, we should make sure to document it nearby the Methods section on docs.meteor.com as well.

**Comment by stubailo** [comment]
Yeah I'm pretty sure it's only documented in like the github readme of validated method or something. Or maybe in the method guide article

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
