### ISSUE TITLE
Document 'login details object, with the attempted login type' in Accounts

### ISSUE THREAD

**Issue by avalanche1** [meteor/docs#190]
As of release 1.6.1
Client side Accounts.onLogin callbacks now receive a login details object, with the attempted login type (e.g. { type: password } after a successful password based login, { type: resume } after a DDP reconnect, etc.)
https://github.com/meteor/meteor/pull/9512

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
