### ISSUE TITLE
Error trying to start hexo instance

### ISSUE THREAD

**Issue by tonycastle** [meteor/docs#223]
> hexo-site@0.0.0 start C:\Users\tonyc\Documents\Projects\Documentation\docs
> npm run build && chexo meteor-hexo-config -- server

> hexo-site@0.0.0 build C:\Users\tonyc\Documents\Projects\Documentation\docs
> jsdoc/jsdoc.sh && chexo meteor-hexo-config -- generate

ERROR: Unable to find the source file or directory **C:\jsdoc.sh**
There are no input files to process.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hexo-site@0.0.0 build: `jsdoc/jsdoc.sh && chexo meteor-hexo-config -- generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hexo-site@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tonyc\AppData\Roaming\npm-cache\_logs\2018-03-04T11_08_11_848Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hexo-site@0.0.0 start: `npm run build && chexo meteor-hexo-config -- server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hexo-site@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tonyc\AppData\Roaming\npm-cache\_logs\2018-03-04T11_08_11_864Z-debug.log

C:\Users\tonyc\Documents\Projects\Documentation\docs>

Anyone know why it is looking for C:\jsdoc.sh.  I'm running Windows 10.

**Comment by abernix** [comment]
The path is certainly questionable, but I think that's actually just the way it shows in the stack-trace.  Ultimately, even if it could find the problem the [`jsdoc/jsdoc.sh` script](https://github.com/meteor/docs/blob/master/jsdoc/jsdoc.sh) (as found from the root of this project) won't execute on Windows.  This is unfortunate, and I apologize that Windows wasn't a consideration here!  The `jsdoc.sh` script makes the scanning of source files substantially quicker by narrowing down the JSDoc scope to just files which include the specific JSDoc [tokens we're looking for](https://github.com/meteor/docs/blob/b5134c01b5ac2f627fa275ae27af579dd519ca8f/jsdoc/jsdoc.sh#L15).

It wouldn't be too difficult to convert that (above linked) script to be a Node script, perhaps using the [`simple-git`](https://npm.im/simple-git) package. There are a number of examples [here in their docs](https://www.npmjs.com/package/simple-git#async-await-with-simple-gitpromise).  Would you be willing to help make this happen?

If not, as an easy alternative, I believe (though haven't tried) you can just temporarily change [the `build` script in the `package.json`](https://github.com/meteor/docs/blob/b5134c01b5ac2f627fa275ae27af579dd519ca8f/package.json#L30) to:

```json
  "build": "jsdoc -t jsdoc/docdata-jsdoc-template -c jsdoc/jsdoc-conf.json && chexo meteor-hexo-config -- generate",
``

It will be slower since it needs to traverse all of the files in the repository, but it _should_ work.

Please let us know how it goes!  And thanks for trying to make a contribution!

**Comment by PolarisWT** [comment]
Windows has some interesting issues when using this setup.  And honestly, I could not make it work full without having the generated `data.js` and the `names.json` files imported from my OSX.  None the less, here are the steps I took to get them running.  Maybe someone can figure out a more streamlined method...

#### package.json (scripts block with modifications) 
```json
  "scripts": {
    "build": "jsdoc -t jsdoc/docdata-jsdoc-template -c jsdoc/jsdoc-conf.json && chexo meteor-hexo-config -- generate",
    "clean": "hexo clean; rm data/data.js data/names.json",
    "test": "npm run clean; npm run build",
    "predeploy": "npm run build",
    "deploy": "hexo-s3-deploy",
    "start": "meteor npm run build && chexo meteor-hexo-config -- server"
  }
```
(note: I am using `meteor npm` with the current version of Meteor 1.7.0.3).  Using global npm gave tremendous amount errors with relation to jsdoc, hexo, and chexo. (usually in the form similar to:
```cmd
ERROR Local hexo not found in C:\meteor\docs
ERROR Try running: 'npm install hexo --save'
```

#### Console commands:
##### From https://github.com/meteor/docs
- `git clone git@github.com:meteor/docs.git`
- `cd docs`
- `git submodule update --init`
##### Windows hack
- __Copy/paste__ [`data.js`](https://gist.github.com/PolarisWT/3e2279837c77566d9547c6930e24fb77#file-data-js) and [`names.json`](https://gist.github.com/PolarisWT/3e2279837c77566d9547c6930e24fb77#file-names-json) into `./data/`
    - Note: These are static files generated Jun 26 2018 for Meteor 1.7.  Anyone using this as a reference will need to obtain updated files for newer releases of meteor!
- `meteor npm install`
- `meteor npm start`

**Comment by kakadais** [comment]
I've got same issue.
npm install has a bunch of errors and data.js is not created.
MacOS 11.1 

Any progress?

**Comment by filipenevola** [comment]
Hi @kakadais, what are you trying to do? 

The project is working as you can see many new PRs with builds almost every week in our docs.

As this is a very old issue please open a new one if you are having issues so you can specify your issues.
