### ISSUE TITLE
Most links within the body text appear to be broken

### ISSUE THREAD

**Issue by rhettlivingston** [meteor/docs#24]
The links within the body text that point to locations within the documentation appear to all be broken. I'm using Chrome on Ubuntu.

For example, in the [documentation for Meteor.publish](https://docs.meteor.com/api/pubsub.html#Meteor-publish), there are links to "added", "changed", and "removed" that don't work. The "added" link's target is https://docs.meteor.com/api/pubsub.html#publish_added. The "this.added" link in the sidebar has the value https://docs.meteor.com/api/pubsub.html#Subscription-added and works fine.

I stuck to links with targets within the section in that example because that is the simplest case, but the link to Collection.Cursor which is across sections in the text above that is broken too.

I'm having trouble believing that this is an issue that was either knowingly accepted or simply missed. It's too basic. But, I refreshed and even opened another browser (Firefox) to be sure I was using a different cache and the behavior didn't change.

I'd also note that I'm getting a strange behavior of seeing the old documentation style when I awake my computer from sleep and the browser had been left showing a page from the new documentation. I then hit F5 and the new documentation style reappears. Perhaps I'm getting some strange mix of old and new documentation.

**Comment by tmeasday** [comment]
No, this is a legitimate bug, that was simply missed. I focused principally on making external links into the docs work, given the new page structure; it didn't occur to me that internal links would have a *different* problem, but now I think about it, it's kind of obvious.

I'll have to take some time to fix this on Monday.

> I'd also note that I'm getting a strange behavior of seeing the old documentation style 

This is appcache. I think browsers are just really buggy in their support for it. (or we are doing something very wrong with it).

**Comment by BudgieInWA** [comment]
It seems that old style links don't work either. http://guide.meteor.com/accounts.html links to http://docs.meteor.com/#/full/accounts_oncreateuser. Clicking the link or pasting the link directly into the address bar causes the route to change to http://docs.meteor.com/#/full//full/accounts_oncreateuser with the main "Introduction" page being rendered.

**Comment by tmeasday** [comment]
Thanks for the reports guys. Both issues are now fixed.

**Comment by tmeasday** [comment]
Let me know if you see any further broken links
