### ISSUE TITLE
Contributing info placement

### ISSUE THREAD

**Issue by lorensr** [meteor/docs#26]
From my observations (of myself 😳) I'm guessing a lot of people who A) submit issues, or even B) submit PRs don't read `Contributing.md`s. 

There are 5 places to consider:
- `readme`
- `contributing`
- issue template
- pr template
- "Please review the guidelines for contributing to this repository." link to `contributing` that appears above issues and PR forms

Atm we have:
- Guide
  - readme just links to guide, 
  - contributing talks about PRs. 
- Docs
  - readme: links to docs.meteor, links to `contributing`, how to run locally
  - contributing to meteor documentation in general – docs, guide, tutorials. PRs _and_ issues, becoming a maintainer
- Meteor 
  - [contributing](https://github.com/meteor/meteor/blob/devel/Contributing.md#documentation) links to  https://github.com/meteor/docs

To make it more likely for people to read the info, I'd like to move the content of docs and guide `contributing`s to `readme`s and just have a link in `contributing` that points to `readme`. Maintain the first `readme` CTA as the site link, as in current docs `readme`.  Docs readme will have the extra general sections, and both will have some duplicated hexo running and editing syntax rules. Table of contents so it's not overwhelming. No issue templates. Pr templates short and tactical, like https://github.com/meteor/guide/pull/440/files And then also linking from `todos/readme` and `tutorials/readme` to `docs/readme`.

**Comment by tmeasday** [comment]
There's also this section: http://guide.meteor.com/#guide-concepts

I agree completely with you. I realised this was a problem as I wrote the `docs/Contributing.md` file but I wanted to make sure we had *something* up before we posted the blog post. I think we can rationalize this a lot a make it easier to navigate. 

In terms of the best execution of this, I think there are two things that are common and perhaps best not duplicated:
  - Overall "contributing to meteor documentation in general" document (currently docs/Contributing.md)
  - Overall "meteor documentation style" which is probably more or less current guide/Contributing.md.

I agree everything is simple enough that it's not worth both projects having separated readmes / contributing files. Perhaps it's best to just have:

- docs/README:
  - link to docs / 1 line description [ALSO add a section to docs/index.html analagous to http://guide.meteor.com/#guide-concepts]
  - how to run locally
  - meteor documentation style
  - becoming a docs contributor


- guide/README:
  - link to guide / 1 line description
  - how to run locally
  - [LINK TO DOCS]: meteor documentation style
  - [LINK TO DOCS]: becoming a docs contributor

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
