### ISSUE TITLE
Document usage of .meteorignore 

### ISSUE THREAD

**Issue by axelvaindal** [meteor/docs#262]
There is a lack of documentation on `.meteorignore` both in the docs and in the guide.
It is only mentioned in the [FR](https://github.com/meteor/meteor-feature-requests/issues/5) and in the [changelog](https://docs.meteor.com/changelog.html#v152120170926).

Documentation should probably just explain the usage of the file and a common example (as it is clearly the same as `.gitignore` or `.npmignore` developers do know about).

First discussion from this [issue](https://github.com/meteor/meteor/issues/9773#issuecomment-376660783) where a Meteor user was looking for this feature without knowing it already existed.

**Comment by skirunman** [comment]
Not sure where this documentation could or would be located in the [Meteor API Docs](https://docs.meteor.com). However, I think it might make more sense to document this in the [Build System](https://guide.meteor.com/build-tool.html) section of the Meteor Guide.

I'm going to a PR in the Meteor Guide and reference this issue so hopefully this can be closed.

**Comment by axelvaindal** [comment]
Sure thing, we originally decided to track this here on @hwillson suggestion, but I agree this would be more suitable in the Guide.
Let's just close this issue when the Guide got the new section about `.meteorignore` :slightly_smiling_face:

**Comment by lorensr** [comment]
Merged, thanks for reporting! https://github.com/meteor/guide/pull/896
