### ISSUE TITLE
Linting: add VS Code to list of editors

### ISSUE THREAD

**Issue by tblong** [meteor/docs#27]
I was able to get things working with VS Code by following the [Installing and running ESLint](http://guide.meteor.com/code-style.html#eslint-installing) instructions and installing the VS Code [ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).  Perhaps this setup could be added to the guide section [Integrating with your editor](http://guide.meteor.com/code-style.html#eslint-editor).

**Comment by tmeasday** [comment]
Sounds great! Could you send a pull request?

**Comment by tblong** [comment]
Done meteor/guide#461.  Sorry for adding this question here instead of the guide repo; hadn't had my first beer of the evening I guess
