### ISSUE TITLE
Facts!

### ISSUE THREAD

**Issue by abernix** [meteor/docs#33]
Perhaps the `facts` package should be documented?  It's currently only briefly talked about here, but can be quite helpful – but is a bit advanced at the moment (docs could help make this a lot easier to understand):

https://github.com/meteor/docs/blob/version-NEXT/long-form/oplog-observe-driver.md#how-to-tell-if-your-queries-are-using-oplogobservedriver

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
