### ISSUE TITLE
Should not forbid rescaling viewport

### ISSUE THREAD

**Issue by abernix** [meteor/docs#34]
@awwx commented on [Wed May 25 2016](https://github.com/meteor/meteor/issues/7121)

> &lt;meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, **user-scalable=no"**&gt;

Please, please, please: do not turn off user-scalable.

Not all of us have eyes that can read tiny fonts.

**Comment by lorensr** [comment]
Yeah, I'm unable to pinch zoom on iOS. Seems like an impt accessibility feature? @dominicnguyen
