### ISSUE TITLE
Search misses some stuff (API method in code snippet)

### ISSUE THREAD

**Issue by JesperWe** [meteor/docs#35]
I made no extensive checking but the one thing I tested failed:

Search for **_isapptest_** in the guide. No results.
Go to testing section, press Ctrl-F and search **_isapptest_** find it as expected.

**Comment by tmeasday** [comment]
@maxiloc (I'm not sure who is best to pull in from Algolia here). Is there something we need to do to configure what is being indexed? 

@JesperWe is referring to the string `Meteor.isAppTest` on this page: http://guide.meteor.com/testing.html

**Comment by maxiloc** [comment]
In fact the configuration is open source and it's prettry straight forward => https://github.com/algolia/docsearch-configs/blob/master/meteor_guide.json

I added it to the config to add code tag. It works fine on our playground
![image](https://cloud.githubusercontent.com/assets/1689007/15587890/a5ea4d0e-238b-11e6-80bc-b183954fa10c.png)

but on the website

![image](https://cloud.githubusercontent.com/assets/1689007/15587928/cf64efe0-238b-11e6-8c89-b7ebc9c17ea6.png)

the record containing isapptest is there but isapptest does not show up

**Comment by tmeasday** [comment]
@maxiloc -- looks like it's working great. I should try and configure the search results to show the text snippet somehow, but it is linking to the right place.

I've created a similar PR for the docs: https://github.com/algolia/docsearch-configs/pull/48

**Comment by JesperWe** [comment]
It seems searches in the API docs show snippets and link to the search hit, but in the Guide you get only the section title?

**Comment by maxiloc** [comment]
@JesperWe Can you give me an example ?

**Comment by JesperWe** [comment]
Apologies, after looking closer I realize that you get snippets with hit highlight in the result if search hit is in a section header, but not if it is in running text. Then you only get a section link, and no hit highlight when you click. 

This is poor UX to me, because I have to ctrl-F again to actually find where in the section I was linked to the hit is.

But this is not what this issue is about. The issue of this issue (hrrm) has been fixed, so I guess it can be closed.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
