### ISSUE TITLE
Use Hypothesis for commenting/annotating docs

### ISSUE THREAD

**Issue by mitar** [meteor/docs#38]
I think it would be great to be able to use [Hypothesis](http://hypothes.is/) for commenting/annotating docs.

**Comment by lorensr** [comment]
adds these three buttons to top-right of site:

![image](https://cloud.githubusercontent.com/assets/251288/15619172/8c655564-2420-11e6-8b37-54ea1609d565.png)

top one opens sidebar with highlights and comments. don't need account for reading comments, but do need to create one (w/ password) for submitting. 

one issue is I don't think I'd want the highlighting to be on by default, and when it's not on, a user would have to go exploring to find the sidebar and know that there are comments there.

**Comment by mitar** [comment]
I think highlighting is good to be on by default, why not? So that one can learn that there is some extra resource available.

**Comment by lorensr** [comment]
Doesn't look as clean. Could get messy/crowded if there were a lot of
highlights/comments. But could work, and could probably customize styles.

**Comment by mitar** [comment]
I think with many highlights/comments they switch to something simpler, so it does not consume so much visual attention.

cc @JakeHartnell

**Comment by JakeHartnell** [comment]
> But could work, and could probably customize styles.

Yes you can customize the styles and so that by default highlights are off. There is a minimalist heatmap with tabs on the side showing annotations are present. I haven't worked there for a while so don't know what the latest plans / customization options are. cc @judell @dwhly @robertknight

**Comment by dwhly** [comment]
"I think with many highlights/comments they switch to something simpler, so it does not consume so much visual attention"

Currently we do not change strategy when there are more or less highlights.  

Here are some config params for the sidebar, such as disabling highlights by default:
https://hypothes.is/for-publishers/

**Comment by lorensr** [comment]
Extreme example:

![image](https://cloud.githubusercontent.com/assets/251288/15620485/75cd8a26-2428-11e6-9b6d-5b09b82d8988.png)

I guess I do like Medium highlighting

**Comment by lorensr** [comment]
See also https://forums.meteor.com/t/annotated-guide/25749

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
