### ISSUE TITLE
Spacebars references?

### ISSUE THREAD

**Issue by JesperWe** [meteor/docs#39]
The spacebars github repo used to contain a very useful readme.md.
This file now says it has been incorporated in the docs.
Except all the links are confused. 
1. The link in the github readme is wrong. I submitted a PR for this.
2. The Templates section of the API docs has two links referencing the Spacebars readme. 
   One points to the Athmosphere package, and the other one just points back to itself.

I tried editing these, but it looks like there is some auto-magic stuff supposed to be going on with the #pkg_spacebars reference, but that's not working....? So I left it and submit this issue instead.

**Comment by abernix** [comment]
The link you PR'd in meteor/meteor#7132 should actually work as-is but it seems the redirect it broken.

But yea, you're the third person this week with this problem.

**Comment by tmeasday** [comment]
The old link did work, it took you here: http://docs.meteor.com/api/templates.html#spacebars (not really the correct place, thanks for fixing it @JesperWe).

The fact that that section has links to `#pkg_spacebars` that go nowhere is a bigger problem. Just deployed a fix for that. They should now redirect to `packages/spacebars.html`.

**Comment by abernix** [comment]
Since this has been moved over to Blaze, I believe this can be closed.  The links are in place to get developers to the right place, which I think should be sufficient.
