### ISSUE TITLE
Document how to properly use dynamic expressions with imports

### ISSUE THREAD

**Issue by hwillson** [meteor/docs#394]
This has come up several times now in `meteor/meteor` issues. We should consider documenting how to leverage dynamic expressions with `import`'s (likely somewhere in the [dynamic-import](https://docs.meteor.com/packages/dynamic-import.html) section). A detailed explanation of how to do this can be found in https://github.com/meteor/meteor/pull/8327#issuecomment-280876264, and https://github.com/meteor/meteor/issues/8744 is an example of one of the recent issues that outline the confusion around this.

Migrated from https://github.com/meteor/guide/issues/641.

**Comment by alejandroiglesias** [comment]
I just stumbled upon trying to use a dynamic expression without knowing why it was failing. This should move forward into the docs please.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

**Comment by coagmano** [comment]
Yeah I think it was solved by my PR a long long time ago and we just forgot to close this issue 😆
