### ISSUE TITLE
Options in DDP.connect isn't documented.

### ISSUE THREAD

**Issue by laosb** [meteor/docs#46]
Posted by @ilacyero in `meteor/meteor` as meteor/meteor#7156 .

> I had a problem to detect the connected state of DDP client connection.
> I find in the documentation how to add this callback. I must debug the initialize to see the options and >its onConnected options. Please try to add in documentation.

```
const connection = DDP.connect(config, {
  onConnected() {
    console.log('connected');
  }
});
```

**Comment by lorensr** [comment]
http://docs.meteor.com/api/connections.html#DDP-connect

![image](https://cloud.githubusercontent.com/assets/251288/15800768/96eb1ccc-2a50-11e6-95fd-489931a7b4ba.png)

@tmeasday when there's an unlisted `@param` that isn't underscored, is it generally meant to be private, or just hasn't been documented yet? 

There are a lot of options:

![image](https://cloud.githubusercontent.com/assets/251288/15800785/08deafba-2a51-11e6-8a7a-4071c9eb8a4f.png)
https://github.com/meteor/meteor/blob/master/packages/ddp-client/livedata_connection.js#L29-L42

**Comment by tmeasday** [comment]
I think the second.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
