### ISSUE TITLE
server-render docs incomplete / not clear.

### ISSUE THREAD

**Issue by thatgibbyguy** [meteor/docs#464]
Hi, I'm attempting to learn SSR with the server-render package, but the docs make it very unclear what I'm doing. For example:

```
import App from "/imports/Server.js";

onPageLoad(sink => {
  sink.renderIntoElementById("app", renderToString(
    <App location={sink.request.url} />
  ));
});
```

What does `/imports/Server.js` do? Is it a router? What would it look like? There's literally no other mention of that file anywhere else in the documentation.

The same follows on the client example. It seems to me like this is simply not a maintained package.

**Comment by skirunman** [comment]
I believe `App` is just a generic reference to what would be your application that you want rendered server-side and that `/imports/Server.js` is the server entry point for your application. I know this is old, but hope you figured it out so this can be closed.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
