### ISSUE TITLE
Alternate Installation For Windows Not Working

### ISSUE THREAD

**Issue by sankarshanarao** [meteor/docs#471]
When the instructions given in the link https://github.com/meteor/docs/blob/version-NEXT/long-form/alternate-windows-installation.md is followed and meteor is opened in cmd, it throws a node error "Cannot find module './tool-env/install-promise.js'".

**Comment by axelvaindal** [comment]
I think the documentation is outdated, considering Meteor now uses [chocolatey](https://chocolatey.org/install) for the installation process. In this [thread](https://chocolatey.org/install) are explained the reason `chocolatey` was adopted over the old installer, and maybe this should be marked as deprecated.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
