### ISSUE TITLE
Sending Download link as HTML

### ISSUE THREAD

**Issue by manwithadodla** [meteor/docs#483]
I’m trying to send a download link via Meteor Email. There is that option to send html but clicking the link does nothing. The parameter I send as html is `message`:

```
var href = 'data:text/json;charset=utf-8,' + encodeURIComponent(data)
var message = '<a href='+href+ 'download="assessment_data.json">Download Assessment Data</a>'
```

**Comment by lorensr** [comment]
I think href needs to be a URL, and a space before download.

This repo is for documentation maintenance—please ask future questions on StackOverflow, thanks!
