### ISSUE TITLE
meteor create --minimal Flag missing from API Docs

### ISSUE THREAD

**Issue by aadamsx** [meteor/docs#489]
In the Meteor API Docs version 1.7 there is no listing for the meteor create name --minimal flag

There are only: DEFAULT, --BARE, --FULL

![image](https://user-images.githubusercontent.com/5341158/43864809-580aac2c-9b26-11e8-8bd4-de4107292821.png)

I don't know what package --minimal has

**Comment by brooksbecton** [comment]
Hey! 
I made that table before and wouldn't mind adding `--minmal` info

I'm on it! 🐱‍💻

**Comment by brooksbecton** [comment]
PR here: https://github.com/meteor/docs/pull/504
