### ISSUE TITLE
Ban the words JUST, EASY and SIMPLE from the docs

### ISSUE THREAD

**Issue by kdekooter** [meteor/docs#495]
Please please please don't use these words or variants thereof anymore. It is annoying, puts newbies off. And a lot of times it is actually not just easy & simple. Let your readers be the judge if something is simple or easy.

**Comment by abernix** [comment]
@kdekooter We completely agree, and I'm certainly aware that their use is present in the current documentation, and even more so in the [Meteor Guide](https://guide.meteor.com) [[GitHub](http://github.com/meteor/guide)].

We'd really appreciate the help from the community to remove and re-write any sentences which use that over-simplification and unfair trivializing of information; removing references to such terminology is certainly something we would accept pull requests for!  That said, I'll close this issue (your message is very much received!), but we'd rather avoid just a broad, sweeping issue for something that we already have our eyes out for.

**Comment by kdekooter** [comment]
Fair enough. Here is the first PR: https://github.com/kdekooter/guide/pull/1

**Comment by abernix** [comment]
Great! Could you open this as a PR against the Guide repository?  It's currently a PR on your own fork of the Guide repository, so we're not able to review it or merge it.

**Comment by kdekooter** [comment]
Sorry about that. Consider it done! https://github.com/meteor/guide/pull/887
