### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by lorensr** [meteor/docs#5]
It's gone! It'd be particularly useful now that it's no longer a single page.

**Comment by tmeasday** [comment]
Yes, this will come soon, in the pipeline

**Comment by tomasz-nolberczak** [comment]
Hi @tmeasday, IMO search functionality is one of the most necessary things right now (before new layout there was helpful CTRL + F command). It is hard to find something among many of single pages. Please do it first and help other Meteor developers during their work ;)

**Comment by dominicnguyen** [comment]
Thanks for your patience everyone. v1 of docs search is now live. Please test and report issues.

**Comment by tomasz-nolberczak** [comment]
Looking good. But it would be better when div.aa-suggestion had cursor pointer on hover.

**Comment by tmeasday** [comment]
@dominicnguyen did you catch the above suggestion?

**Comment by dominicnguyen** [comment]
yup, on the roadmap

**Comment by abernix** [comment]
The last remaining hover issue has been resolved.
