### ISSUE TITLE
Missing documentation of mobile config App.settings

### ISSUE THREAD

**Issue by skirunman** [meteor/docs#505]
In this commit https://github.com/meteor/meteor/commit/b830665a1fdbe51d1afa33d9cba056d0390f8201 it looks like support was added to get settings info from `settings.json` file to `mobile-config.js` when building for Cordova in Meteor 1.7. 

However, this feature does not seem to documented in `docs/source/api/mobile-config.md` so it needs to be added.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
