### ISSUE TITLE
Where is ReactiveDict package documented?

### ISSUE THREAD

**Issue by skirunman** [meteor/docs#52]
This seems like a pretty core package and is a better replacement for Session, which is documented and only exists for legacy purposes as it is built using ReactiveDict anyway. Looks like there was an old issue https://github.com/meteor/meteor/issues/4100

Also, ReactiveDict has some functions not in Session such as all, clear and delete.

Session and ReactiveDict both have a setDefault function that is not documented in Session docs either.

**Comment by lorensr** [comment]
Not currently documented. Should go after http://docs.meteor.com/api/reactive-var.html

**Comment by coagmano** [comment]
I've just started a PR with a first pass at adding docs for this.

Text of page here: #507
And the `apibox`'s will be filled with content from here: meteor/meteor#10273
