### ISSUE TITLE
Formatting issues for field names/types

### ISSUE THREAD

**Issue by mjmasn** [meteor/docs#53]
Noticed this on http://docs.meteor.com/api/connections.html but there may be others. 

<img width="943" alt="screen shot 2016-06-20 at 14 01 57" src="https://cloud.githubusercontent.com/assets/2977095/16195023/9a0ff57a-36ef-11e6-826d-f00d0a335b7a.png">

I was wondering why the first field was now called `connectedBoolean` before realising that the field types are merged with the field names. So it's actually `connected` [a boolean].

**Comment by lorensr** [comment]
That doesn't look good, thanks for submitting 😊 Looks like an issue with the site theme, which we'll track over here: https://github.com/meteor/hexo-theme-meteor/issues/20
