### ISSUE TITLE
Document Fiber semantics of observe/observeChanges

### ISSUE THREAD

**Issue by Torgen** [meteor/docs#594]
Suppose you observe a cursor on the server, e.g.

```coffee
Meteor.startup ->
  handle = someCollection.find(someQuery).observeChanges
    added: (id, fields) ->
      # do something
```

0. If there are two documents, A and B, already in the collection that match the query, and the `added` call for A yields, can the `added` call for B occur before the call for A resumes and completes? (I happen to know the answer is no, and the existing doc suggests this, which is why I numbered this question 0, but since a callback wrapped in `bindEnvironment` passed to non-Fiber-aware code will return when it yields, this may be less obvious than it seems.)

1. If, after the initial results are delivered, there come to be two documents, A and B, which satisfy the query, and the `added` callback for A yields, will the `added` callback for B occur before the call for A resumes and completes? (I believe the answer is no--each handle gets its own fiber. I don't know if I have any evidence for this.)

2. If, after the initial results are delivered, there comes to be a document A which satisfies the query, and the `added` call for A calls `Meteor.defer`, passing a function which yields; then after that yield, there comes to be a document B which satisfies the query, will the `added` call for B occur before the deferred function resumes and completes? (I believe the answer is yes--deferred functions run in their own fiber.)

    a. If so, and the `added` callback for B also defers a function, will that function be called before the deferred function for A resumes and completes? (I believe the answer is yes--each deferred function runs in its own fiber. Is there a limit? e.g. a pool of fibers used for `defer` and `setTimeout`?)

3. Suppose instead we observe two different cursors in the same `Meteor.startup` call. After the initial results for both are delivered, a document A comes to satisfy the query of the first cursor, and its `added` call yields. Then a document B comes to satisfy the query of the second cursor. Will the `added` call for B occur before the call for A resumes and completes? (I believe the answer is yes--the fiber is attached to the handle, not to the `Meteor.startup` call in which the handle was created.)

    a. Suppose instead we observe the same cursor twice. After the initial results are delivered, a document A comes to satisfy the cursor's query. If the `added` call for the first handle yields, will the `added` call for the second handle occur before the call for the first handle resumes and completes? (I believe the answer is yes--the fiber is per handle, not per cursor.)

If I'm wrong about 1, that has correctness implications for operations that must be serialized; if I'm right, it has performance implications for operations that can be paralleled. (2 and 3 relate to strategies I might use to do so.) It would be nice if I could be confident in which it was.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
