### ISSUE TITLE
[idea] separating doc generation into a re-usable doc generator.

### ISSUE THREAD

**Issue by trusktr** [meteor/docs#602]
Seems like the doc generation here in the docs repo would be nice as a generic standalone doc generator. It would be useful for anyone wanting to document their code from jsdocs/markdown.

One example of a doc generator is [`Docma`](https://onury.io/docma/). The stuff here in this repo could be an alternative (once made generic).

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
