### ISSUE TITLE
testModule is not mentioned in the description of 'meteor test'

### ISSUE THREAD

**Issue by GuillaumeTech** [meteor/docs#609]
Hi ! 
Thanks a lot for open sourcing your work!

The propriety "testModule", that allows you to specify which test file to run is not mentioned  in the API guide https://guide.meteor.com/testing.html#test-modes.

I believe it should be mentioned in the API guide since the propriety "testModule" changes the behavior of the `meteor test` command, as explained in the tutorial (section "New in Meteor 1.7") : https://www.meteor.com/tutorials/react/testing

Cheers !

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
