### ISSUE TITLE
Remove `Meteor.users` `profile` usage

### ISSUE THREAD

**Issue by abernix** [meteor/docs#61]
@ffxsam commented on [Sat Jan 16 2016](https://github.com/meteor/guide/issues/196)

The guide says:

> The best way to store your custom data onto the Meteor.users collection is to add a new uniquely-named top-level field on the user document.

I thought it was encouraged to use the `profile` object, per the official docs?

```
Meteor.users.update(userId, {$set: {'profile.nickname': 'MegaBob'}});
```

---

@stubailo commented on [Sun Jan 17 2016](https://github.com/meteor/guide/issues/196#issuecomment-172276397)

No in fact there are multiple sections in the guide that say not to use profile. We should change the docs.

---

@ffxsam commented on [Sun Jan 17 2016](https://github.com/meteor/guide/issues/196#issuecomment-172276430)

Oh shoot. And here I just misinformed someone. :disappointed: Thanks for the tip.

---

@stubailo commented on [Thu Apr 07 2016](https://github.com/meteor/guide/issues/196#issuecomment-206623848)

Moved to meteor/meteor

**Comment by abernix** [comment]
Just moving it _again_ from meteor/meteor#6728 (the landlord over there is the worst! :wink:)

Originally in meteor/guide#196.  :smile:

**Comment by ffxsam** [comment]
You know what's interesting about adding custom data to a user: you can't add anything until after the user is already created. But at creation time, you can still use `profile` which is incorrect. So I wrote a little routine to handle this, so I can add first name, last name, etc to profile, but it moves it to the right spot for me.

```js
Accounts.onCreateUser((options, user) => {
  /*
   * The official Meteor Guide recommends not storing things in user.profile. So
   * this will mutate any newly created user and just put profile information at
   * the root level which is recommended. So when using Accounts.createUser,
   * go ahead and use profile, and this will handle fixing it.
   *
   * Reference: http://guide.meteor.com/accounts.html#dont-use-profile
   */
  return { ...user, ...options.profile };
});
```

**Comment by lorensr** [comment]
Here are places I'm seeing profile used in docs. 

Is `name` or anything else auto-added to the profile by any of the `accounts-*` packages?

```
Accounts.emailTemplates.enrollAccount.subject = function (user) {
    return "Welcome to Awesome Town, " + user.profile.name;
};
```

example user doc:

```
  profile: {
    // The profile is writable by the user by default.
    name: "Joe Schmoe"
  },
```

also:

![image](https://cloud.githubusercontent.com/assets/251288/16903434/2f8f773a-4c4c-11e6-930d-a771329803d8.png)

**Comment by stubailo** [comment]
Yes, `name` is added automatically by the accounts packages.

**Comment by lorensr** [comment]
@ffxsam I don't see any other places in docs saying to use `profile`, do you?

**Comment by ffxsam** [comment]
Well, it's mentioned all over http://docs.meteor.com/api/accounts.html and http://docs.meteor.com/api/accounts-multi.html.

**Comment by lorensr** [comment]
It seems like that's just describing how the code works, which I wouldn't want to take out until the code changes?

**Comment by ffxsam** [comment]
Ok, I'm now lost.. I think I've lost track of what this discussion was actually about. ;)

I think the confusion is that the Meteor Guide says to [not use profile](https://guide.meteor.com/accounts.html#dont-use-profile). But the docs have examples of using it.

**Comment by lorensr** [comment]
> I think the confusion is that the Meteor Guide says to not use profile. But the docs have examples of using it. 

Since that's where the accounts packages put the `name`, I think we should leave some info about it in the docs. We do say:

"Do not store anything on profile that you wouldn’t want the user to edit unless you have a deny rule on the Meteor.users collection."

Maybe there are more places where we should put a similar disclaimer/recommendation?

> And is it being considered that profile be officially removed from the docs?

I wouldn't remove it from docs until the code changes, at which point we'll probably just not have it be default-writeable (and remove the Guide recommendation to not use it). That would be breaking, which is why the change hasn't been made yet.

**Comment by ffxsam** [comment]
>Since that's where the accounts packages put the `name`

Could you elaborate on this? In what scenario does creating a user automatically populate `profile.name`? I've always had to manually add it, e.g.:

```js
Accounts.createUser({ email: 'blah@blah', password: 'test', profile: { name: 'Bob' } });
```

**Comment by lorensr** [comment]
Don't know, I'm going by https://github.com/meteor/docs/issues/61#issuecomment-233414344 😊 `accounts-facebook` might be an example

**Comment by ffxsam** [comment]
@stubailo What's the official stance then? Can we still use `profile` for things like name (or split out into first/last name)? Or should that just go right onto the user object? The only advantage I see for using `profile` is that it doesn't require a subscription to access data inside of it. But I just wasn't sure if MDG is saying we should be careful about what we put in `profile`, or that we should outright not use it.

**Comment by tmeasday** [comment]
The guide is more up-to-date than the docs, so this is the latest thinking: https://guide.meteor.com/accounts.html#dont-use-profile

**Comment by StorytellerCZ** [comment]
The docs seem to me to hint about the dangers of using profile. Should we add a link to the guide for more info or any mentions altogether then?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
