### ISSUE TITLE
Upsert documentation is misleading

### ISSUE THREAD

**Issue by mhlmhl** [meteor/docs#639]
The API documentation of [upsert ](https://docs.meteor.com/api/collections.html#Mongo-Collection-upsert)is misleading, if not downright wrong.

The documentation says that "Returns an object with keys numberAffected (the number of documents modified) and insertedId (the unique _id of the document that was inserted, if any)."  Also, the callback function is "called with an error object as the first argument and, if no error, the number of affected documents as the second."

This implies that one could do:

`const result = collection.upsert(...) `

and the callback function would be something like:
`(error, count) => { ...}`

BUT actual experience says that in fact no synchronous result is returned from upsert, and the callback function is actually:

`(error, {numberAffected, insertedId}) => {...}`

So this is a bug report for the documentation.  (Maybe it will save some other developer the couple of hours that I wasted on this today.)

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
