### ISSUE TITLE
Accounts.addEmail and Accounts.createUser - better docs / add feature / bug

### ISSUE THREAD

**Issue by alan-pl** [meteor/docs#640]
Accounts.addEmail and Accounts.createUser -- these API methods allow the email argument to be any non-empty string. This is not intuitive. I suggest one or more of these fixes: 
- document this behavior (simplest, easiest)
- a server-side config setting could be available, like "rfcEmailsOnly: boolean", or "emailValidator: function", etc.
- this could even be regarded as a bug, on the grounds that "addEmail" implies that the argument must be a valid email address. Maybe the methods should run a stricter validation, but that could be a breaking change.

**Comment by filipenevola** [comment]
hi @alan-pl are you still willing to write a PR documenting this better?

**Comment by alan-pl** [comment]
Nope

**Comment by filipenevola** [comment]
As the docs are saying that is a `String` I believe it's ok.
