### ISSUE TITLE
Implementing Accounts Without Wrapping a Blaze component in React

### ISSUE THREAD

**Issue by victorfds** [meteor/docs#641]
There should is a other example to create Accounts in React without using Blaze component.

On the React Guide on eighth step, can be found here: https://www.meteor.com/tutorials/react/adding-user-accounts, is used Blaze to exemplify just one way to deal with Accounts in React. If you search for another UI you can't found in the Meteor docs anywhere.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
