### ISSUE TITLE
Question: Use fork or local clone as the source for /code?

### ISSUE THREAD

**Issue by wildhart** [meteor/docs#643]
Is there a way to use my own fork (or even better, a local clone) as the source of the API code?

I've tried:
```
$ git clone https://github.com/wildhart/docs.git --branch wildhart/10469 --single-branch
$ cd docs
************
// edit .gitmodules to contain:
[submodule "themes/meteor"]
	path = themes/meteor
	url = https://github.com/meteor/hexo-theme-meteor.git
[submodule "code"]
	path = code
	url = https://github.com/wildhart/meteor.git
	branch = fix-issue-10469
**************
$ git submodule update --init
Cloning into 'code'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 204849 (delta 16), reused 22 (delta 12), pack-reused 204818
Receiving objects: 100% (204849/204849), 74.86 MiB | 2.48 MiB/s, done.
Resolving deltas: 100% (156867/156867), done.
Checking connectivity... done.
fatal: reference is not a tree: d8563dab467ae7559597cd0a4345e5008e630daa
Unable to checkout 'd8563dab467ae7559597cd0a4345e5008e630daa' in submodule path 'code'
```

I get the same error even if I omit the `branch` line from `.gitmodules`

I just want to see how my API documentation within the code looks...

**Comment by coagmano** [comment]
Git doesn't actually use the `.gitmodules` file to track remote refs.
Easiest is to `cd` into the code folder and manually checkout the fork from there

**Comment by wildhart** [comment]
Thanks, that seems to work.  Although its quite difficult to get it to update after changing anything in the `/code` folder - I have to delete all of `/data/*`, `/public/*` and change something on the relevant page in `/source`, then re-run `npm start`.
