### ISSUE TITLE
Add meteor publish --update to the docs

### ISSUE THREAD

**Issue by jankapunkt** [meteor/docs#692]
I just found via `meteor publish --help` that I can update the README without the need for publishing a new package vis `meteor publish --update`.

This is a great feature, since I forgot a line of code in the README. However, this is not documented in the docs and I think it should be added to the docs, [since it's missing there](https://docs.meteor.com/commandline.html#meteorpublish). I can provide a PR, if you like.

**Comment by lorensr** [comment]
Sounds good, thanks!

**Comment by filipenevola** [comment]
Please do @jankapunkt

**Comment by jankapunkt** [comment]
@filipenevola I forgot to link it (see https://github.com/meteor/docs/pull/685) it should be merged already.

**Comment by jankapunkt** [comment]
Sorry totally confused an already merged PR with this the one I wanted to start for this issue. Lots of things happened this month :sweat_smile:

**Comment by jankapunkt** [comment]
Related PR: #693
