### ISSUE TITLE
Documentation about pollingIntervalMs and pollingThrottleMs is unclear

### ISSUE THREAD

**Issue by laosb** [meteor/docs#72]
**Moved from meteor/meteor#7538**

**Original  by @ignl**

I am not sure if documentation is correct for [Collection-find](http://docs.meteor.com/api/collections.html#Mongo-Collection-find). In this [blog post](http://info.meteor.com/blog/tuning-meteor-mongo-livedata-for-scalability) settings for Livedata optimization are called pollingInterval and pollingThrottle. Also I am not sure if default for pollingIntervalMs is really 10s? I tried various combinations but couldn't get it to work on meteor 1.4.0.1. Currently I try like this serverside:

`messages.find({'metadata.thread': threadId}, {sort: {'date' : sort}, limit: limit, pollingThrottle: 12000, pollingInterval: 12000});`

I expect a new message to be pushed to other client every 12s, but it seems meteor just updates them immediately anyway. Is this a correct way to do it?

**Comment by ignl** [comment]
Any news on this?

**Comment by abernix** [comment]
Unfortunately, this particular doc issue has to be in `meteor/meteor` since it's a JSDoc comment – so closing this and reopening that one.  Also, I'm still hoping for feedback over there to my #2 bullet-point in this comment: https://github.com/meteor/meteor/issues/7538#issuecomment-246956226
