### ISSUE TITLE
Nested Helper explanation needs example or two

### ISSUE THREAD

**Issue by abernix** [meteor/docs#73]
@Maxhodges commented on [Sun Mar 01 2015](https://github.com/meteor/meteor/issues/3841)

No matter how many times I read this, I can't be sure what it's saying. Please provide an example or two.

> Nested Helper: If there is a positional argument followed by other (positional or keyword arguments), the first argument is called on the others using the normal helper argument calling convention.

---

@Maxhodges commented on [Sun Mar 01 2015](https://github.com/meteor/meteor/issues/3841#issuecomment-76603172)

is this right?

Passing helperB to helperA
`{{helperA helperB}}`

Passing 'helperB with argument x' to helperA
`{{helperA helperB x}}`

Passing 'helperB with argument x=false' to helperA
`{{helperA helperB x=false}}`

---

@stubailo commented on [Tue Mar 10 2015](https://github.com/meteor/meteor/issues/3841#issuecomment-78150288)

@Maxhodges, looks like you have it correct. I agree that this is confusing. Can you point me to the part of the documentation that has that sentence?

---

@abernix commented on [Wed Aug 03 2016](https://github.com/meteor/meteor/issues/3841#issuecomment-237196322)

I'm moving this to the docs repo.  This is in the Spacebars docs here: https://docs.meteor.com/packages/spacebars.html

@Maxhodges I realize this issue is super old but I'm sure the community would appreciate a pull-request to make this more clear if you get a chance.  I think the examples you provided are helpful too.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
