### ISSUE TITLE
Cannot navigate back to new API docs from older API docs

### ISSUE THREAD

**Issue by brucejo75** [meteor/docs#730]
## Repro
1. Choose dropdown on API docs home page to select a previous version.  You can see all versions
2. Go to a previous version, e.g. **[v1.4](https://docs.meteor.com/v1.4)**.

**Result**: The dropdown does not include any versions newer that v1.4.
**Expected**: all versions to continue to be in the dropdown

**Comment by StorytellerCZ** [comment]
:thinking: I think we could solve this by updating the versions in configs of all the branches. I'll do that after dinner.

**Comment by StorytellerCZ** [comment]
Yep that fixed it. Will do that for the rest of the branches.

**Comment by StorytellerCZ** [comment]
Should be fixed for most branches now.

**Comment by brucejo75** [comment]
@StorytellerCZ, looks like it is fixed for versions 1.9 and up (which is OK, I am supposing)

Issues:
v1.9 is missing v1.10.
Versions 1.10 & 1.11 act strangely.
1.10 tops out at1.11, if you press 1.11 it will send you to v2.3
1.11 tops out at 1.12, if you press 1.12 it will send you to v2.3

**Comment by StorytellerCZ** [comment]
Yeah, I will be fixing these up occasionally as part of other issues.
