### ISSUE TITLE
Logo messed up when navigating directly to older versions of the docs

### ISSUE THREAD

**Issue by brucejo75** [meteor/docs#731]
## Repro
1. go to [v1.12 docs](https://docs.meteor.com/v1.12). 

**Result**: the logo is not sized correctly.
**Note 1**: all versions prior to v2.0 have this issue. all newer docs work fine.  e.g v2.0+

**Comment by StorytellerCZ** [comment]
Fixed in 1d09c22aba0db728c5651f3e3d1b53f7a0cf5a30

**Comment by brucejo75** [comment]
@StorytellerCZ, Lookin good!
