### ISSUE TITLE
All docs on one site

### ISSUE THREAD

**Issue by mitar** [meteor/docs#8]
Please create a way to have all docs displayed on one large website. This really allows quick jumping back and forth, searching, navigating. It also works offline nicely.

**Comment by lorensr** [comment]
1. The search (#5) will hopefully be as good as find in page. 
1. In what ways is single page better for jumping and navigating? 
1. We might want to recommend http://devdocs.io/ for viewing offline?

**Comment by mitar** [comment]
> The search (#5) will hopefully be as good as find in page. 

Hm, I prefer my own browser search over search engines. :-) And it does not work offline, probably.

> In what ways is single page better for jumping and navigating? 

Hm, at least it is faster to scroll then click. Also it is easier to skim sections and find one you want than having to guess where stuff is in some hard-coded categorization.

> We might want to recommend http://devdocs.io/ for viewing offline?

I think it should be pretty easy to render all markdown documents into one huge HTML file and link to it? Not sure if we need external service for that?

**Comment by tmeasday** [comment]
The whole thing on one page is bad because it kills mobile browsers amongst other things.

We'd like to figure a way to get the whole thing into a pdf or better yet a single page for printing (from which a pdf could be generated), we've discussed this a fair bit on the guide as well https://github.com/meteor/guide/issues/166.

PRs welcome ;)

**Comment by mitar** [comment]
I am saying that it should be an option, not necessary even a default. And yes, it would be useful for printing as well. :-)

**Comment by lorensr** [comment]
I think the killing mobile browsers might have been the fact that it was a *meteor* app displaying a large page – I think a static page might be fine

**Comment by tmeasday** [comment]
Well maybe. But there are other benefits to the multi-page too.

**Comment by brucejo75** [comment]
I would like to add to @mitar use case.  How many hits do you get from mobile?  How many from desktop?  By hits I mean any click on the page, not page loads.

I think I hit this page 50-100 times a day on a good development day.  It is my homepage for the Chrome browser.  I am not sure what the mobile scenario is exactly, but I would bet it is a verification of something while in a meeting or talking with someone else.

The core use case is while writing code, it may be unwise to optimize too much for the mobile case at the expense of the core case.

Thanks for listening!

**Comment by tmeasday** [comment]
I think it'd be pretty easy to create a hexo plugin that sets up a route that renders all pages in one big document. Not going to have time to look at it in the near future but would happily help someone figure it out!

**Comment by brucejo75** [comment]
Any chance we could post the old docs while this gets worked out?

**Comment by tmeasday** [comment]
I wrote up an issue here if someone wants to take a stab at this: https://github.com/meteor/hexo-theme-meteor/issues/12

**Comment by tmeasday** [comment]
@brucejo75 you can check out `meteor/meteor` `master` branch and run the local docs app if you want the old site.

**Comment by brucejo75** [comment]
@tmeasday, thanks Tom!  I went into the docs directory and ran meteor.  Then brought up the page.  It is v1.2.1.

Is the v1.3 stuff still available?  A lot of stuff is missing.  Like [Accounts.userCreate](https://github.com/meteor/docs/issues/31), funny.

Is there something I can do to get it to point to v1.3?

thanks!

**Comment by brucejo75** [comment]
Urp... never mind.  I forgot to update to master branch (still pretty new to git, etc).  All is great now!

I still think it may be valuable to post this page somewhere.

thanks again.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
