### ISSUE TITLE
Include meteor/meteor/History.md in Docs

### ISSUE THREAD

**Issue by abernix** [meteor/docs#91]
Currently, if you get a Meteor update to a new version, I'm not sure there is any clear path for you to see what has changed unless you're aware that GitHub is _the_ place to go.  There's [a History.md](https://github.com/meteor/meteor/blob/master/History.md) which is well maintained, but it's hard to find as GitHub might not be the first place many users go.  Aside from GitHub, Meteor.com would seem like the first logical place to head.

But even then, it appears the process would be something like this for many (most?) users:

* Go to [Meteor.com](http://Meteor.com)
* (optional, but likely, path) Click on **Install**
 * See no Release Notes
 * Try the Docs/Guide links there?
* Click on **Developer** (at top)
 * Hmm, maybe Docs? or Guide?
* Get to Docs/Guide
 * Guide: See Migration Guides, but nothing per version.  Click Docs (top right)
 * Docs: See nothing helpful.  Click Guide.
 * Maybe go to Forums?  But forums usually only has major releases.
* Try to find the code source?
 * No link to the `meteor/meteor` GitHub
 * Google?

It would be best if Meteor.com had a <sub>tiny</sub> link to Release Notes under the "Install" button.  Or at least on the Install page.  Linking to the GitHub Repo might be abrupt UX (with no return path), so a nice option might be the Docs.  Unfortunately, Docs doesn't have Release Notes to link to right now.

Since the `code` is already a submodule of `docs`, and `code` has a `History.md`, it seems like it might be possible to import this into Docs.

Seed planted by: meteor/meteor#7881 & meteor/meteor#7870, both opened this week and semi-related to: meteor/meteor#6730.

**Comment by lorensr** [comment]
What about when a new version is downloaded and when someone updates, we print a link to the relevant section of History.md, or to the upgrade section of the Guide if there is one?

**Comment by laosb** [comment]
I'm thinking that we should have something automatically generate a rough list for History.md, and if we need to explain the entry further more, just add few words there. So we won't miss some changes or get confused since for now we're modifying entries on a per PR/commit pattern.

**Comment by tmeasday** [comment]
I added this: http://docs.meteor.com/changelog.html

Could probably be better (please improve y'all) but I think it helps anyway. I'll look into get a link on the homepage.

**Comment by tmeasday** [comment]
We'll probably want to be more militant in updating the submodule too so that doesn't get out of sync.

**Comment by abernix** [comment]
@tmeasday This is great!  Agree to agree on the submodule updating – I'll certainly keep my own eyes on it.

@lorensr I think this (as in, a specific link to each new version) could be accomplished right now by amending and setting the banners (using the [`admin set-banners`](https://github.com/meteor/meteor/blob/devel/tools/cli/commands-packages.js#L2485) command) after each release.  However, from what I gather, the need to link to a specific anchor/version in the change log would further complicate the already-complicated release process.  Banners are currently only done on major versions, and in the future I think any time a banner is used, it's certainly reasonable to include the direct link.  As a stopgap measure for smaller releases, perhaps just a link to this new [change log](http://docs.meteor.com/changelog.html) could be added [in this meteor code](https://github.com/meteor/meteor/blob/e86ef3cb47fb4f44a06b35433d94cae4602e7bcc/tools/runners/run-all.js#L364) which is outputted when the an update is complete?  I believe that's the only point where it would need to be displayed.  That would be best for a PR over at `meteor` though.
