### ISSUE TITLE
CSS Error in Safari

### ISSUE THREAD

**Issue by collinhaines** [meteor/docs#93]
While viewing the [Meteor.Error documentation](https://docs.meteor.com/api/methods.html#Meteor-Error), I noticed that the `<code>` block after the error explanation was not rendering line breaks as deemed necessary.

I've determined it is due to `white-space: nowrap;` from `.document-formatting *:not(figure.highlight) pre code` due to Safari always stating `Invalid CSS property declaration at: *`.

Either changing to `white-space` to `pre`, `pre-wrap`, `inherit` or removing the declaration seems to fix the problem. I just don't know where else in the entire API documentation this rule is being used.

[Attached Imgur Album](https://imgur.com/a/SWLni)

**Comment by lorensr** [comment]
Thanks Collin ☺️ Confirmed safari bug & that `white-space` fixes.  @dominicnguyen options:

![image](https://cloud.githubusercontent.com/assets/251288/19413944/2cfcf618-930b-11e6-8817-b653f67c7f9a.png)

**Comment by abernix** [comment]
So a `white-space: pre` override provides what I believe to be the desired result, in Safari, but doesn't work in Chrome.  The culprit of this `white-space: nowrap` getting added though is the [`.ellipsized` mixin](https://github.com/meteor/hexo-theme-meteor/blob/b7d9c60e272187f84ab430c5e9ffbfa21f91faef/source/style/_util/text.import.less#L15).

That being said, I'd vote to remove [the `.ellipsized` mixin from the `code` style here](https://github.com/meteor/hexo-theme-meteor/blob/b7d9c60e272187f84ab430c5e9ffbfa21f91faef/source/style/_global/formatting.less#L140).  While it provides attractive shortening of code lines in the docs, it's not really helpful to the developer viewing the code as you can't "expand it" to see the code (something you probably need).  Also, it fixes this problem.

Thoughts?

**Comment by lorensr** [comment]
sounds good
