### ISSUE TITLE
code example in test

### ISSUE THREAD

**Issue by Denly** [meteor/docs#96]
import { Factory } from 'meteor/factory';
should be 
import { Factory } from 'meteor/dburles:factory';
in all related test code ex. https://guide.meteor.com/testing.html#simple-react-unit-test
not sure it is the problem or my setting tho. my meter has no meteor/factory

**Comment by abernix** [comment]
Thanks for reporting this issue!

I'm guessing this code sample was meant to refer to the `factory` package which is [locally installed in the React `todos` example app](https://github.com/meteor/todos/tree/react/packages/factory).

Someone else would need to clarify if it was okay to use `dburles:factory` here in this example because I'm not sure what the reason is for the local `factory` package - but you're right, this snippet wouldn't have access to it!

**Comment by hwillson** [comment]
No, they can't be directly swapped. The todos `factory` package is different. There was some discussion about merging the todos `factory` and  `dburles:factory` packages together in meteor/todos#119, but for now that work has been put on-hold.

**Comment by abernix** [comment]
Ah, I see.  Ok, so I wonder for the time-being if the best issue would be to either:

0. Link to the [`TodoItem.tests.js` file itself](https://github.com/meteor/todos/blob/e2b367ec145be9cf03b215cea3430626f222f0b6/imports/ui/components/TodoItem.tests.js) so it has some context; or
0. Put a JS-style code comment above those lines, indicating that they are local packages.

🤔 

(Also, I guess this entire conversation should be on the [meteor/guide](https://github.com/meteor/guide/issues) repo.)

**Comment by hwillson** [comment]
I like the idea of implementing both 1 & 2. This question has come up a few times on the forums as well, so the more context we can provide the better!

**Comment by tmeasday** [comment]
I think we should switch to using the public package if possible, especially in the guide.

**Comment by hwillson** [comment]
Thanks @tmeasday - as a super quick workaround I can create a public/published version of the todos `factory` package, and fire in PR's to update todos and the Guide. This is a quick fix - the better longterm fix would be to continue with the ideas mentioned in meteor/todos#138. In the short term however, the quick fix will at least help reduce some confusion. Does this sound okay?

**Comment by tmeasday** [comment]
Sure thing @hwillson

**Comment by hwillson** [comment]
Great - I've created meteor/todos#193 to track this work.

**Comment by abernix** [comment]
Issue moved to [meteor/guide #576](https://github.com/meteor/guide/issues/576) via [**ZenHub**](https://www.zenhub.com/)
