### ISSUE TITLE
To add a table with errors and corresponding error codes

### ISSUE THREAD

**Issue by Akronix** [meteor/docs#99]
Hi!

I'm missing a table to quickly find the errors code (error field inside Meteor.Error Object) of the errors I want to catch. Of course, I'm talking about the errors that are thrown by Meteor built-in functions, not for other errors defined by the user.

**Comment by abernix** [comment]
Thanks for opening this.  I think PRs like your #100 are a great contribution to the Docs, so thank you very much for that.

That being said, I'm not sure there is much value in leaving this here vaguely without specific action areas so I'm going to close it.  If you do have the opportunity to make additional PRs as you come across them, please do!

Also, happy to reopen this if you want to make specific target areas so others could work on it. :smile:

Thanks again!

**Comment by Akronix** [comment]
Ok, let's keep it closed for now.
Thanks!
